apiVersion: v1
kind: ConfigMap
metadata:
  name: order-configmap
data:
  PAYMENT_HOST: "http://payment-service.default.svc.cluster.local/balance/reserve"
  STOCK_HOST: "http://stock-service.default.svc.cluster.local/products/reserve"
  DELIVERY_HOST: "http://delivery-service.default.svc.cluster.local/courier/reserve"
