apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: hw37order
          image: kisuni/hw37order
          ports:
            - containerPort: 8000
          env:
            - name: PAYMENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: PAYMENT_HOST
            - name: STOCK_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: STOCK_HOST
            - name: DELIVERY_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: DELIVERY_HOST
            - name: NOTIFY_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: NOTIFY_HOST
